### ISSUE TITLE
Typing using different languages?

### ISSUE THREAD

**Issue by armaandh** [cadejscroggins/tilde#10]
When I change my Mac's IME to Korean or Japanese, I get an issue where the first key typed is in English, and then the subsequent keys typed are just fine. 
So instead of getting こんにちは（Konnichiwa), you get Kおんにちは because the first key pressed is "k". This can be got around if you hold the right arrow key while typing the first letter (not sure why). Any ideas?

**Comment by xvvvyz** [comment]
I have a hunch. I'll look into it this weekend, but if you want to dig in, I suspect [this line](https://github.com/cadejscroggins/tilde/blob/master/index.html#L924) has something to do with it. Could be wrong.

**Comment by xvvvyz** [comment]
Alright. I made a change that might fix this, but It's hard for me to test.

**Comment by xvvvyz** [comment]
@armaandh can you test this again?

**Comment by armaandh** [comment]
Still seems to be the same issue. If I type a word like "Gangnam" in Korean, which on the keyboard maps to hitting the keys rkdska (강남) <-Gangnam...the result is the first syllable (ㄱ) being replaced with R.

**Comment by armaandh** [comment]
Closing this as everything seems fixed and working!
