### ISSUE TITLE
Default '?' page on page load

### ISSUE THREAD

**Issue by RoyalClem** [cadejscroggins/tilde#11]
I really like this start page - but I LOVE your help/'?' page - would be amazing if you could get the page to load on default with the time/search on the top. I am currently looking though your index right now to see if there is any way to do this currently, but I think it would look look very good.

Quick mockup:

![tidle](https://user-images.githubusercontent.com/24209472/29006114-4ab457ca-7a9e-11e7-8fbb-e745c1aeab1c.png)

**Comment by xvvvyz** [comment]
Definitely possible. I created a branch the does everything except put the search next to the time. It should be pretty simple, but you'll have to style it how you like so I figured I'd leave that to you. Let me know if you have any questions!

https://github.com/cadejscroggins/tilde/tree/demo

**Comment by RoyalClem** [comment]
demo is perfect - exactly what I expected!

**Comment by xvvvyz** [comment]
Awesome (: Gonna close this. Feel free to comment if you have any more questions.
