### ISSUE TITLE
Sites as default page

### ISSUE THREAD

**Issue by ghost** [cadejscroggins/tilde#14]
Hi there,

I love this startpage you've built, but I do have one question. Is there a way I can change the default opening page from the clock to the sites I've configured? 

Thanks!

**Comment by xvvvyz** [comment]
See https://github.com/cadejscroggins/tilde/issues/11. Seems like maybe this should be a setting (:

**Comment by ghost** [comment]
I didn't even think to check closed issues. Thanks!
