### ISSUE TITLE
broken in Edge

### ISSUE THREAD

**Issue by lightrow** [cadejscroggins/tilde#16]
so, straight to the point - typing stuff in doesn't give suggestions ( dynamic colors thing works though ), pressing enter after typing doesn't do anything whatsoever, and the clock upon opening the startpage is completely missing, just a white page. Oh and the help screen is aligned vertically instead of, well, the way it is supposed to be

![screenshot 1](https://user-images.githubusercontent.com/11335104/29832607-a205a50e-8c9d-11e7-9ceb-17ebbdaeef73.png)
![screenshot 2](https://user-images.githubusercontent.com/11335104/29832606-a201be12-8c9d-11e7-8d1c-7c8039e662f8.png)

**Comment by joshua-russell** [comment]
Doesn't work in Safari on a Mac at the moment either.

**Comment by xvvvyz** [comment]
@lightrow @joshua-russell I just tested on edge & safari (latest versions) and everything seems to work with the latest changes. Feel free to create a new issue if a specific bug persists.
