### ISSUE TITLE
Not able to quick select sites

### ISSUE THREAD

**Issue by armaandh** [cadejscroggins/tilde#17]
Not sure if i'm doing something wrong here, but when I visit: [https://cadejscroggins.github.io/tilde/](https://cadejscroggins.github.io/tilde/) and press "?", followed by any of the key sequences, such as 'g' for github on my keyboard, rather than going to the site, it enters the search mode with the letter "G". Experiencing this with tilde on Firefox Chrome and Safari.

**Comment by xvvvyz** [comment]
That's the default behavior (you have to press enter to execute the command). If you don't want to have to do that, there is an [instant redirect](https://github.com/cadejscroggins/tilde/blob/master/index.html#L62) option that you can set to true in the config.

Note that showing the help by pressing `?` doesn't change any functionality (i.e you can still search and enter commands the same way you do on the initial screen).

Let me know if you have any more questions.

**Comment by armaandh** [comment]
Sorry, I completely missed the instant redirect option! Thanks, everything makes sense now.
