### ISSUE TITLE
[Request] Sample theme CSS

### ISSUE THREAD

**Issue by pranav-ram** [cadejscroggins/tilde#20]
Recently came across Tilde, and instantly fell in love with it.

The code references 'file:///home/cade/.cache/wal/colors.css', but this isn't checked in. Could you please upload this file, and/or any other themes you've created so far, to be used as a point of reference?

Thanks

**Comment by xvvvyz** [comment]
Hey! Just saw this, sorry for the late reply. I no longer use a theme file. The main reason to IMO is if you have a tool that automatically generates it for you to match the rest of your desktop better (e.g [wal](https://github.com/dylanaraps/wal#firefox-variables)). Anyway, the only variables Tilde references are `--color-0` and `--color-15`. So you could create a theme file with just:

```css
:root {
  --color0: #fff;
  --color15: #111;
}
```

You might as well just modify the `index.html` file if you're doing it by hand though.
