### ISSUE TITLE
Multiple tabs open when clicking on suggestion

### ISSUE THREAD

**Issue by seanvree** [cadejscroggins/tilde#21]
Dude, this is dope. 

Question - when I type in a query and click on the suggestion, the same link opens in multiple tabs. 

I haven't changed any of the options in the code.

Tested on Chrome 71.0.3578.98 in Windows. 

Happens on your demo site as well. 

thanks!

![annotation 2019-01-17 024702](https://user-images.githubusercontent.com/8906637/51309877-9b57f380-1a02-11e9-8413-43d2e272fbf9.jpg)

**Comment by xvvvyz** [comment]
c035b616622f906b263126d4cf31ee2ed050d67c should fix this. Test it when you get the chance.

Thanks for reporting!

**Comment by seanvree** [comment]
@cadejscroggins  yup, looks good my man. 

This is VERY dope man.   Testing it on my startpage:

https://seanvree.github.io/homepagetest/

**Comment by xvvvyz** [comment]
Sweet! Let me know if you have any questions.

**Comment by seanvree** [comment]
@cadejscroggins  hey brotha, I hit you up on reddit if you don't mind

**Comment by xvvvyz** [comment]
@seanvree you did? I didn't see any messages come through.

**Comment by seanvree** [comment]
@cadejscroggins  nah, I figured it out brotha. Thanks. 

I threw you some credit on my page, is that ok?

https://github.com/seanvree/homepage#credits

**Comment by xvvvyz** [comment]
@seanvree of course!
