### ISSUE TITLE
Problem when creating pass N objects

### ISSUE THREAD

**Issue by milanecode** [cadejscroggins/tilde#24]
Edit: I figured the issue deeper, from the name of categories to the number of them.
The problem is that the startpage stops responding to keys when you create a number of 24 objects/shortcuts. Meaning, 24 of the {name,key,url,search,color}, and defaults to a google search.

**Comment by xvvvyz** [comment]
Hm. I wasn't able to reproduce this. Can you share your changes?

**Comment by milanecode** [comment]
Yes, I just uploaded the .html as temporary repo. (https://github.com/milanecode/tilde_issue)

Edit: Testing it some more, I also found the issue of the help menu not being able to fit the top part of the categories on the help menu once you have to scroll it. The rest is fine, but the top part, with the category names, get's hidden, at least for notebook-sized screens. You can see the problem in this image: [https://imgur.com/UNYId0W](https://imgur.com/UNYId0W) .

Also, thanks for answering on such short notice, I've been using this since that reddit post on 2016.

**Comment by xvvvyz** [comment]
Thanks. It seems you [forgot to add a url for one of the commands](https://github.com/milanecode/tilde_issue/blob/master/index_mila.html#L214). As for the help menu, let me try and come up with a solution for that. I've never had that many commands 😄

**Comment by xvvvyz** [comment]
Here's a simple fix a came up with: https://github.com/milanecode/tilde_issue/pull/1

**Comment by milanecode** [comment]
Yes, is perfect! You're a lifesaver man. The original repo had some personal stuff, so I'll leave the solution here to the help thingy here: 

`@media (min-width: 1000px) {
    .help {
      display: flex;
      padding: 0;
    }`

`@media (min-width: 1500px) {
    .help {
      display: flex;
    }
    .categories {
      grid-template-columns: repeat(5, 220px) 175px;
    }`

Edit: Well, doesn't look so nice since Github deletes whitespace and indentation. My bad. Here is an image of how it should look like: [https://imgur.com/hdKvyiX](https://imgur.com/hdKvyiX)

**Comment by xvvvyz** [comment]
Happy to help (:
