### ISSUE TITLE
^n & ^p key bindings aren't registering on Windows & Linux

### ISSUE THREAD

**Issue by xvvvyz** [cadejscroggins/tilde#3]
Per https://github.com/cadejscroggins/tilde/commit/406217eef8e8ee2da1b8f0d166fc393c9f869631.

**Comment by xvvvyz** [comment]
[It's not looking good](http://stackoverflow.com/questions/7295508/javascript-capture-browser-shortcuts-ctrlt-n-w).

**Comment by jRimbault** [comment]
The cross OS solution would be to bind something other than Ctrl.
Simply binding the arrow keys ? 38 up and 40 down.

**Comment by xvvvyz** [comment]
https://github.com/cadejscroggins/tilde/commit/38eb33bd42d15d589c4aba46919f5cb97a7b59b8

**Comment by jRimbault** [comment]
Seems to work fine now. Thank you for your time ^^

**Comment by xvvvyz** [comment]
Of course (: I'm gonna close this.
