### ISSUE TITLE
Firefox highlighting address bar (Not a bug!)

### ISSUE THREAD

**Issue by FrontierProphet** [cadejscroggins/tilde#32]
This is more logistics than the start page itself, I love the idea and have it as my home page and new tab page in the latest version of Firefox. When I open a new tab or page the address bar is highlighted, and I have to click the screen to use the homepage and have it function. Not a huge deal, but rather annoying. Has anyone else had this same issue or know how to fix it? Or am I just dumb

**Comment by xvvvyz** [comment]
Hey, I don't know if this is something you can change. I personally just keep Tilde open as my first tab and have links open in a new tab so it never goes anywhere. When I want to use Tilde I hit `command + 1` on macOS to go to the first tab.

**Comment by FrontierProphet** [comment]
The term for where the cursor lands in firefox is "focus", and there is an option to change the focus to the webpage as opposed to the address bar if you use the [new tab over-ride extension](https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/)

Before hand I was just editing the .cfg directly, but this works better. Just learning this and thought I would share for others, thanks!
