### ISSUE TITLE
global search function is broken

### ISSUE THREAD

**Issue by draculalaa** [cadejscroggins/tilde#33]
**Describe**
Global search doesn't work, unless opened as a local file.

**Reproduce**
1. visit [https://tilde.xvvvyz.xyz/](https://tilde.xvvvyz.xyz/).
2. type "duck" and hit return.
3. will enter the address "https://tilde.xvvvyz.xyz/?q=duck", instead of "https://duckduckgo.com/?q=duck".

**Soluation**
I know little about Javascript so my soluation may looks stupid.
Replace follow:
```
      const [baseUrl, rest] = Search.#splitUrl(CONFIG.defaultSearchTemplate);
      const url = Search.#formatSearchUrl(baseUrl, rest, query);
      return { query, search: query, url };
```
with:
```
      const url = this.#hasProtocol(query) ? query : `https://duckduckgo.com/?q=${query}`;
      return { query, search: query, url };
```

I hope it helps. Love your work.

**Comment by xvvvyz** [comment]
Good catch, thank you for opening this. Fixed in https://github.com/xvvvyz/tilde/commit/609760aa60be2c2fd8e6d57729077ab78fc78c34.
