### ISSUE TITLE
Broken in Opera

### ISSUE THREAD

**Issue by mbluemer** [cadejscroggins/tilde#4]
The better question is probably why on Earth am I using Opera as my web browser.... Regardless though I decided to try it out and Tilde is just completely broken. 

Used [this](https://addons.opera.com/en/extensions/details/custom-new-tab-page/?display=en) addon to access the page whenever I open a new tab. Basically when hitting enter nothing happens. Then input box is cleared but it doesn't take me anywhere. Since it's built off of chromium I'd assume the javascript wouldn't act any different so maybe it's the addon.

I don't expect work to be put into this but I figured I'd at least document it and if I find a workaround I'll update the issue.

**Comment by xvvvyz** [comment]
Interesting. Are you getting any console errors?

**Comment by mbluemer** [comment]
I am a total idiot. Made an issue without even thinking to check that. Turns out I had settings on that denied sites from using localstorage... Thanks for the help!

**Comment by xvvvyz** [comment]
No worries! Enjoy 😄
