### ISSUE TITLE
Help overlay formatting issue

### ISSUE THREAD

**Issue by xvvvyz** [cadejscroggins/tilde#6]
> I cannot get the help (key: ‘?’) to display in several columns as is showned in the github readme; it just shows one long column centered in the page.

**Comment by pablocobelli** [comment]
Currently using Safari, version 10.0.3 (12602.4.8) on macOS Sierra. I can confirm this happens in Safari but does not occur in Chrome, in which the help layout appears as depicted in the image currently shown in the README file for the project. 

I guess this is related to (apparently known) issues with flex (the flexible box layout module) and safari; some of which are mentioned [here](https://teamtreehouse.com/community/strange-css-flexbox-flexwrap-issue-in-safari-bug
) and [here](https://stackoverflow.com/questions/34250282/flexbox-safari-bug-flex-wrap),  for instance. Although those links also presumably provide solutions to this issue, I haven't tested any of them yet.

**Comment by xvvvyz** [comment]
Testing it on Safari 10.1.1, and it works as expected. Are you able to update?

**Comment by pablocobelli** [comment]
That's great news then, I knew it was on my side. I'll update, test it, and come back to tell you. Thanks for your quick answer.

**Comment by pablocobelli** [comment]
Ok, I can confirm it's ok now with Safari 10.1.2. Tilde is great, thanks again.

**Comment by xvvvyz** [comment]
Awesome. Gonna close this (:
