### ISSUE TITLE
Mobile Friendly?

### ISSUE THREAD

**Issue by ylor** [cadejscroggins/tilde#9]
Can't search with a mobile browser as there's no way to make input field focused. Any way to make it more friendly?

**Comment by xvvvyz** [comment]
Didn't expect anyone to really use this on mobile :P I'll see what I can do this weekend.

**Comment by xvvvyz** [comment]
Just pushed some updates. You can now click on the clock to show the search input. Let me know what you think.

**Comment by ylor** [comment]
Wonderful! Thanks so much for taking the time.
